spring.datasource.url=jdbc:mysql://localhost:3306/srms_db
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Automatically structures tables based on Java Model classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true