# 1. Database URL Configuration (Targets your local machine port 3306 and database srms_db)
spring.datasource.url=jdbc:mysql://localhost:3306/srms_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=@admin123

# 2. Database Driver Framework Setup
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Automated Table Creation Strategy (The Magic Step!)
# 'update' tells Spring Boot to look at your Student.java file and build the table for you automatically
spring.jpa.hibernate.ddl-auto=update

# 4. Debug Mode (Prints out the behind-the-scenes SQL commands in your IDE console terminal window)
spring.jpa.show-sql=true